const BASE_PATHS = {
  AUTH: 'accounts/',
  ACCOUNTS: 'accounts/',
  PERSON: 'person/',
  CORE: 'core/',
  ADMISSION: 'admission/',
  PROGRAM: 'program/',
  FILE: 'manager/',
  REPORT: 'report/'
}

export const ENDPOINTS_CONFIG = {
  AUTH: {
    LOGIN: `${BASE_PATHS.AUTH}user/login/`,
    EMAIL_ACCESS_CODE: `${BASE_PATHS.AUTH}user/email-code/`,
    VERIFY_ACCESS_CODE: `${BASE_PATHS.AUTH}user/verify-code/`,
    RECOVERY_PASSWORD: `${BASE_PATHS.AUTH}user/recovery-password/`,
    EMAIL_APPLICANT: `${BASE_PATHS.AUTH}user/email-applicant/`,
    REFRESH_SESSION: `${BASE_PATHS.AUTH}user/refresh-session/`,
    LOGIN_WITH_GOOGLE: `${BASE_PATHS.AUTH}user/google_sign_in/`
  },
  ACCOUNTS: {
    ACCESS_MENU: `${BASE_PATHS.ACCOUNTS}user/accessmenu/`,
    CREATE_ACCOUNT: `${BASE_PATHS.ACCOUNTS}user/create-account/`,
    CHANGE_PASSWORD: `${BASE_PATHS.ACCOUNTS}user/change-password/`,
    EMAIL_CHANGE: `${BASE_PATHS.ACCOUNTS}user/email-change/`,
    MENU: `${BASE_PATHS.ACCOUNTS}user/access_menu/`
  },
  MODULES: {
    MODULE: `${BASE_PATHS.ACCOUNTS}module/`,
    MENU: `${BASE_PATHS.ACCOUNTS}menu/`,
    SUBMENU: `${BASE_PATHS.ACCOUNTS}submenu/`,
    SECTION_MENU: `${BASE_PATHS.ACCOUNTS}sectionmenu/`,
    USER: `${BASE_PATHS.ACCOUNTS}user/`,
    USER_ACCESS: `${BASE_PATHS.ACCOUNTS}useraccess/`,
    USER_ROLE: `${BASE_PATHS.ACCOUNTS}userrole/`,
    AUDIT: `${BASE_PATHS.ACCOUNTS}audit/`,
  },
  PERSON: {
    PERSON: `${BASE_PATHS.PERSON}person/`,
    //Not used
    DOCUMENT_TYPE: `${BASE_PATHS.PERSON}documenttype/`,
    PERSON_TYPE: `${BASE_PATHS.PERSON}persontype/`,
    MARITAL_STATUS: `${BASE_PATHS.PERSON}maritalstatus/`,
    ACADEMIC_DEGREE: `${BASE_PATHS.PERSON}academicdegree/`,
    JOB_SECTOR: `${BASE_PATHS.PERSON}jobsector/`,
    ACADEMIC_INFO: `${BASE_PATHS.PERSON}academicinfo/`,
    ACADEMIC_INFO_LIST: `${BASE_PATHS.PERSON}academicinfo/get_academic_info/`,
    LANGUAGE_INFO: `${BASE_PATHS.PERSON}idiominfo/`,
    JOB_INFO: `${BASE_PATHS.PERSON}jobinfo/`,
    JOB_INFO_LIST: `${BASE_PATHS.PERSON}jobinfo/get_job_info/`,
    PERSON_INFO: `${BASE_PATHS.PERSON}contactinfo/`,
    PROGRESS_INFO: `${BASE_PATHS.PERSON}person/progress_info/`,
    PERSON_FILES: `${BASE_PATHS.PERSON}files/`,
    PERSON_FILES_PENDING: `${BASE_PATHS.PERSON}person/files_requirements/`,
    GET_PERSON_USER: `${BASE_PATHS.PERSON}person/get_person/`,
    UPDATE_PHOTO: `${BASE_PATHS.PERSON}person/update_photo/`
  }
  //   CORE: {
  //     ADMIN_UNITY: `${BASE_PATHS.CORE}adminunity/`,
  //     RECTORAL_RESOLUTION: `${BASE_PATHS.CORE}rectoralresolution/`,
  //     DIRECTORAL_RESOLUTION: `${BASE_PATHS.CORE}directoralresolution/`,
  //     STAFF_TYPE: `${BASE_PATHS.CORE}stafftype/`,
  //     STAFF: `${BASE_PATHS.CORE}staff/`,
  //     COUNTRY: `${BASE_PATHS.CORE}country/`,
  //     UBIGEO: `${BASE_PATHS.CORE}ubigeo/`,
  //     HEADQUARTER: `${BASE_PATHS.CORE}headquarter/`,
  //     OCCUPATION: `${BASE_PATHS.CORE}occupation/`,
  //     ADMIN_JOB_OCCUPATION: `${BASE_PATHS.CORE}adminjoboccupation/`,
  //     PERIOD: `${BASE_PATHS.CORE}period/`,
  //     ACTION_TYPE: `${BASE_PATHS.CORE}actiontype/`,
  //     STUDENT_FILE_HISTORY: `${BASE_PATHS.CORE}studentfilehistory/`,
  //     UBIGEO_FILTERDATA: `${BASE_PATHS.CORE}ubigeo/filterdata/`,
  //     COUNTRY_FILTERDATA: `${BASE_PATHS.CORE}country/filterdata/`,
  //     FACULTY: `${BASE_PATHS.CORE}adminunity/`,
  //     UNIVERSITY: `${BASE_PATHS.CORE}university/`,
  //     PROFESIONAL_SCHOOL: `${BASE_PATHS.CORE}school/`,
  //   },
  //   ADMISSION: {
  //     APPLICANT_FILE: `${BASE_PATHS.ADMISSION}applicantfile/`,
  //     APPLICANT_FILE_DOCUMENTS: `${BASE_PATHS.ADMISSION}applicantfile/applicant_documents/`,
  //     ASSIGN_EVALUATION: `${BASE_PATHS.ADMISSION}assignevaluation/`,
  //     CONVOCATORY: `${BASE_PATHS.ADMISSION}convocatory/`,
  //     CONVOCATORY_LIST: `${BASE_PATHS.ADMISSION}convocatory/convocatorylist/`,
  //     EVALUATION: `${BASE_PATHS.ADMISSION}evaluation/`,
  //     PROMOTION_CONVOCATORY: `${BASE_PATHS.ADMISSION}promotionconvocatory/`,
  //     PROMOTION_REQUIREMENT: `${BASE_PATHS.ADMISSION}promotionrequirement/`,
  //     REQUIREMENT: `${BASE_PATHS.ADMISSION}requirement/`,
  //     TIMELINE: `${BASE_PATHS.ADMISSION}timeline/`,
  //     TIMELINE_CONVOCATORY: `${BASE_PATHS.ADMISSION}convocatory/convocatorytimeline/`,
  //     MODALITY: `${BASE_PATHS.ADMISSION}modality/`,
  //     PROGRAMS_CONVOCATORY: `${BASE_PATHS.ADMISSION}promotionconvocatory/convocatoryprograms/`,
  //     HEADER_PROGRAM: `${BASE_PATHS.ADMISSION}promotionconvocatory/program_head/`,
  //     INFO_PROGRAM: `${BASE_PATHS.ADMISSION}promotionconvocatory/program_info/`,
  //     VALIDATE_PAY: `${BASE_PATHS.ADMISSION}applicantfile/validate_payment/`,
  //     APPLICANT_REQUIREMENT: `${BASE_PATHS.ADMISSION}applicantfile/applicant_requirements/`,
  //     APPLICANT_FILE_SAVE: `${BASE_PATHS.ADMISSION}applicantfilesave/`,
  //     APPLICANT_FILE_LIST: `${BASE_PATHS.ADMISSION}applicantfile/`,
  //     APPLICANT_RECORDS: `${BASE_PATHS.ADMISSION}applicantfile/applicant_records/`,
  //     ADMISSION_MODALITY: `${BASE_PATHS.ADMISSION}admissionmodality/`,
  //     APPLICANT_CHECK: `${BASE_PATHS.ADMISSION}applicantfile/applicant_check/`,
  //     ATTACH_FILE: `${BASE_PATHS.ADMISSION}applicantfile/attach_requirement/`,
  //     PROMOTION_CONVOCATORY_BULK: `${BASE_PATHS.ADMISSION}bulks/promotionconvocatorybulk/`,
  //     DIMENTION_REQUIREMENT: `${BASE_PATHS.ADMISSION}dimensionrequirement/`,
  //   },
  //   PROGRAM: {
  //     INFO_STUDY_PLAN: `${BASE_PATHS.PROGRAM}study-plan/studyplan_info/`,
  //     PROGRAM: `${BASE_PATHS.PROGRAM}program/`,
  //     PROGRAM_TYPE: `${BASE_PATHS.PROGRAM}program-type/`,
  //     STUDY_PLAN: `${BASE_PATHS.PROGRAM}study-plan/`,
  //     COURSE: `${BASE_PATHS.PROGRAM}course/`,
  //     COURSE_REQUIREMENT: `${BASE_PATHS.PROGRAM}course-requirement/`,
  //     KNOWLEDGE_AREA: `${BASE_PATHS.PROGRAM}knowledge-area/`,
  //     PROGRAM_STUDY_PLAN: `${BASE_PATHS.PROGRAM}program/programs_study_plan/`,
  //   },
  //   FILE: {
  //     FILE_TYPES: `${BASE_PATHS.FILE}filetypes/`,
  //     REQUIREMENT_FILES: `${BASE_PATHS.FILE}requirementfiles/`,
  //     FILES: `${BASE_PATHS.FILE}files/`,
  //     PERSON_FILES_PENDING: `${BASE_PATHS.FILE}files/person_files_requirements/`,
  //   },
  //   REPORT: {
  //     GET_CV_PERSON: `${BASE_PATHS.REPORT}hoja-vida/`,
  //     GET_APPLICATION_HISTORY: `${BASE_PATHS.REPORT}application-history`,
  //   },
  //   BULKS: {
  //     EVENT_CALL_BULK: `${BASE_PATHS.ADMISSION}bulks/timelinebulk/`,
  //   },
  //   ADMIN: {
  //     CONVOCATORY_SUMMARY: `${BASE_PATHS.ADMISSION}convocatory/convocatory_summary/`,
  //     DISTRIBUTION_PROGRAM: `${BASE_PATHS.ADMISSION}convocatory/distribution_by_program/`,
  //     LAST_INROLLEMENT: `${BASE_PATHS.ADMISSION}applicantfile/applicants_convocatory/`,
  //     PROGRAM_FILTER: `${BASE_PATHS.ADMISSION}convocatory/program_filter/`,
  //   },
}
